type StatusVariant =
  | 'new-request'
  | 'quote-sent'
  | 'booking-confirmed'
  | 'trip-info-missing'
  | 'in-progress'
  | 'completed'

type AvatarData = Readonly<{
  alt: string
  fallback?: string
}>

type MockLead = Readonly<{
  tripId: string
  tripStatus: string
  tripStatusVariant: StatusVariant
  itinerary: string
  departureDate: string
  contact: string
  contactCompany: string
  salesAgents: AvatarData[]
  aircraftAvailability: string
  totalPrice: string
  lastThread: string
  lastUpdate: string
  [key: string]: unknown
}>

export const PIPELINE_STAGES = [
  { label: 'All leads', count: 845 },
  { label: 'New requests', count: 500 },
  { label: 'Quotes', count: 300 },
  { label: 'Booking', count: 25 },
  { label: 'Booked trips', count: 15 },
  { label: 'Day of flight', count: 5 },
] as const

export const MOCK_LEADS: MockLead[] = [
  {
    tripId: 'TRP-3102',
    tripStatus: 'New request',
    tripStatusVariant: 'new-request',
    itinerary: 'KTEB - KLAS',
    departureDate: 'Mar 15, 2026',
    contact: 'Sarah Mitchell',
    contactCompany: 'Apex Group',
    salesAgents: [{ alt: 'John Davis' }, { alt: 'Maria Lopez' }],
    aircraftAvailability: '3 available',
    totalPrice: '$85,400',
    lastThread: 'New charter request — 8 PAX',
    lastUpdate: '10 min ago',
  },
  {
    tripId: 'TRP-2991',
    tripStatus: 'Quote sent',
    tripStatusVariant: 'quote-sent',
    itinerary: 'KVNY - KSFB',
    departureDate: 'Mar 18, 2026',
    contact: 'David Chen',
    contactCompany: 'Meridian Capital',
    salesAgents: [{ alt: 'Sarah Kim' }],
    aircraftAvailability: '5 available',
    totalPrice: '$62,800',
    lastThread: 'RE: Round trip quote',
    lastUpdate: '25 min ago',
  },
  {
    tripId: 'TRP-2847',
    tripStatus: 'Booking confirmed',
    tripStatusVariant: 'booking-confirmed',
    itinerary: 'KPBI - KTEB',
    departureDate: 'Mar 12, 2026',
    contact: 'Jessica Taylor',
    contactCompany: 'Northwind Aviation',
    salesAgents: [{ alt: 'Tom Anderson' }, { alt: 'Lisa Park' }, { alt: 'Mike Chen' }],
    aircraftAvailability: '1 confirmed',
    totalPrice: '$124,500',
    lastThread: 'Booking confirmed — Global 6000',
    lastUpdate: '1 hr ago',
  },
  {
    tripId: 'TRP-3056',
    tripStatus: 'Trip info missing',
    tripStatusVariant: 'trip-info-missing',
    itinerary: 'KLAX - KMIA',
    departureDate: 'Mar 12, 2026',
    contact: 'Michael Roberts',
    contactCompany: 'Sterling Partners',
    salesAgents: [{ alt: 'Amy Chen' }],
    aircraftAvailability: '2 available',
    totalPrice: '$78,200',
    lastThread: 'Missing passenger manifest',
    lastUpdate: '2 hrs ago',
  },
  {
    tripId: 'TRP-3108',
    tripStatus: 'New request',
    tripStatusVariant: 'new-request',
    itinerary: 'KJFK - EGLL',
    departureDate: 'Mar 22, 2026',
    contact: 'Emily Parker',
    contactCompany: 'Vista Aviation',
    salesAgents: [{ alt: 'John Davis' }],
    aircraftAvailability: '4 available',
    totalPrice: '$178,000',
    lastThread: 'Transatlantic request — 4 PAX',
    lastUpdate: '3 hrs ago',
  },
  {
    tripId: 'TRP-2965',
    tripStatus: 'Quote sent',
    tripStatusVariant: 'quote-sent',
    itinerary: 'KSFO - KDEN - KDAL',
    departureDate: 'Mar 16, 2026',
    contact: 'Robert Zhang',
    contactCompany: 'Pacific Holdings',
    salesAgents: [{ alt: 'Sarah Kim' }, { alt: 'Tom Anderson' }],
    aircraftAvailability: '3 available',
    totalPrice: '$94,600',
    lastThread: 'RE: Multi-leg itinerary',
    lastUpdate: '5 hrs ago',
  },
  {
    tripId: 'TRP-3089',
    tripStatus: 'Trip info missing',
    tripStatusVariant: 'trip-info-missing',
    itinerary: 'KBOS - KIAD',
    departureDate: 'Mar 10, 2026',
    contact: 'Amanda Foster',
    contactCompany: 'Crestline Group',
    salesAgents: [{ alt: 'Amy Chen' }, { alt: 'Lisa Park' }],
    aircraftAvailability: '0 available',
    totalPrice: '$42,800',
    lastThread: 'Urgent — Aircraft swap needed',
    lastUpdate: '6 hrs ago',
  },
  {
    tripId: 'TRP-2903',
    tripStatus: 'Booking confirmed',
    tripStatusVariant: 'booking-confirmed',
    itinerary: 'KHOU - MMUN',
    departureDate: 'Mar 14, 2026',
    contact: 'James Wilson',
    contactCompany: 'Pinnacle Corp',
    salesAgents: [{ alt: 'Maria Lopez' }],
    aircraftAvailability: '1 confirmed',
    totalPrice: '$56,900',
    lastThread: 'Customs pre-clearance arranged',
    lastUpdate: '8 hrs ago',
  },
  {
    tripId: 'TRP-3115',
    tripStatus: 'New request',
    tripStatusVariant: 'new-request',
    itinerary: 'KSDL - KLAS',
    departureDate: 'Mar 11, 2026',
    contact: 'Lisa Novak',
    contactCompany: 'Orion Ventures',
    salesAgents: [{ alt: 'John Davis' }],
    aircraftAvailability: '6 available',
    totalPrice: '$38,500',
    lastThread: 'Charter inquiry — 12 PAX',
    lastUpdate: '1 day ago',
  },
  {
    tripId: 'TRP-3042',
    tripStatus: 'Quote sent',
    tripStatusVariant: 'quote-sent',
    itinerary: 'KDAL - KPBI',
    departureDate: 'Mar 19, 2026',
    contact: 'Thomas Grant',
    contactCompany: 'Atlas Industries',
    salesAgents: [{ alt: 'Tom Anderson' }],
    aircraftAvailability: '2 available',
    totalPrice: '$67,300',
    lastThread: 'Phenom 300 availability check',
    lastUpdate: '1 day ago',
  },
  {
    tripId: 'TRP-3120',
    tripStatus: 'New request',
    tripStatusVariant: 'new-request',
    itinerary: 'KPWK - KMCO',
    departureDate: 'Mar 22, 2026',
    contact: 'Karen Beck',
    contactCompany: 'Summit Advisory',
    salesAgents: [{ alt: 'Sarah Kim' }],
    aircraftAvailability: '4 available',
    totalPrice: '$45,200',
    lastThread: 'Family trip — 5 PAX + pet',
    lastUpdate: '1 day ago',
  },
  {
    tripId: 'TRP-3001',
    tripStatus: 'Trip info missing',
    tripStatusVariant: 'trip-info-missing',
    itinerary: 'KDAL - KLAS',
    departureDate: 'Mar 13, 2026',
    contact: 'Brian Marsh',
    contactCompany: 'Redstone Capital',
    salesAgents: [{ alt: 'Amy Chen' }],
    aircraftAvailability: '2 available',
    totalPrice: '$51,800',
    lastThread: 'Missing catering preferences',
    lastUpdate: '2 days ago',
  },
  {
    tripId: 'TRP-2978',
    tripStatus: 'Quote sent',
    tripStatusVariant: 'quote-sent',
    itinerary: 'KORD - KPBI',
    departureDate: 'Mar 20, 2026',
    contact: 'Nicole Adams',
    contactCompany: 'Vertex Group',
    salesAgents: [{ alt: 'Maria Lopez' }, { alt: 'John Davis' }],
    aircraftAvailability: '3 available',
    totalPrice: '$72,400',
    lastThread: 'RE: Quote revision',
    lastUpdate: '2 days ago',
  },
  {
    tripId: 'TRP-2856',
    tripStatus: 'Booking confirmed',
    tripStatusVariant: 'booking-confirmed',
    itinerary: 'KBNA - KTEB',
    departureDate: 'Mar 11, 2026',
    contact: 'Patrick Sullivan',
    contactCompany: 'Ironclad Corp',
    salesAgents: [{ alt: 'Lisa Park' }],
    aircraftAvailability: '1 confirmed',
    totalPrice: '$58,700',
    lastThread: 'G280 confirmed — FBO notified',
    lastUpdate: '2 days ago',
  },
  {
    tripId: 'TRP-3128',
    tripStatus: 'New request',
    tripStatusVariant: 'new-request',
    itinerary: 'KMIA - TNCM',
    departureDate: 'Apr 5, 2026',
    contact: 'Maria Santos',
    contactCompany: 'Coral Holdings',
    salesAgents: [{ alt: 'Tom Anderson' }],
    aircraftAvailability: '5 available',
    totalPrice: '$89,200',
    lastThread: 'St. Maarten retreat — 6 PAX',
    lastUpdate: '3 days ago',
  },
  {
    tripId: 'TRP-2934',
    tripStatus: 'In progress',
    tripStatusVariant: 'in-progress',
    itinerary: 'KSFO - PHNL',
    departureDate: 'Mar 25, 2026',
    contact: 'Andrew Kim',
    contactCompany: 'Horizon Tech',
    salesAgents: [{ alt: 'Sarah Kim' }, { alt: 'Amy Chen' }],
    aircraftAvailability: '1 pending',
    totalPrice: '$156,000',
    lastThread: 'Updated Hawaii itinerary',
    lastUpdate: '3 days ago',
  },
  {
    tripId: 'TRP-2889',
    tripStatus: 'Booking confirmed',
    tripStatusVariant: 'booking-confirmed',
    itinerary: 'KLAS - KJFK',
    departureDate: 'Mar 10, 2026',
    contact: 'Daniel Foster',
    contactCompany: 'Blackstone Aviation',
    salesAgents: [{ alt: 'Maria Lopez' }],
    aircraftAvailability: '1 confirmed',
    totalPrice: '$98,300',
    lastThread: 'Crew scheduling resolved',
    lastUpdate: '4 days ago',
  },
  {
    tripId: 'TRP-3095',
    tripStatus: 'New request',
    tripStatusVariant: 'new-request',
    itinerary: 'KIAD - LFPG',
    departureDate: 'Apr 2, 2026',
    contact: 'Rachel Moore',
    contactCompany: 'Elysium Partners',
    salesAgents: [{ alt: 'John Davis' }],
    aircraftAvailability: '2 available',
    totalPrice: '$195,000',
    lastThread: 'Paris transatlantic — 8 PAX',
    lastUpdate: '4 days ago',
  },
]
